// export const ADD_ITEM = "ADD_ITEM";
// export const UPDATE_ITEM = "UPDATE_ITEM";
// export const DELETE_ITEM = "DELETE_ITEM";
// export const REDUCE_COUNTER = "REDUCE_COUNTER";
// export const ADD_COUNTER = "ADD_COUNTER";
// export const ADD_TO_CART = "ADD_TO_CART";
// export const EDIT_ITEM = "EDIT_ITEM";
// export const DELETE_FROM_CART = "DELETE_FROM_CART";
// export const ADD_TO_ORDERS = "ADD_TO_ORDERS";

export const SIGN_IN = "SIGN_IN";
export const LOGOUT = "LOGOUT";
export const SIGN_UP = "SIGN_UP";
export const ADD_GROUP = "ADD_GROUP";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const UPDATE_GROUP = "UPDATE_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const UPDATE_MEMBERS = "UPDATE_MEMBERS";
export const UPDATE_CUSTOM_CATEGORY = "UPDATE_CUSTOM_CATEGORY";
